export { default as UiKitInput} from './UiKitInput.vue'
export { default as UiKitSelect } from './UiKitSelect.vue'
export { default as UiKitSkeleton } from './UiKitSkeleton.vue'
export { default as UiKitDrop } from './UiKitDrop.vue'
export { default as UiKitBurger } from './UiKitBurger.vue'
export { default as UiKitPopup } from './UiKitPopup.vue'
export { default as UiKitTextArea } from './UiKitTextArea.vue'
export { default as UiKitPagination } from './UiKitPagination.vue'